[tool.poetry]
name = "jsw-nx"
version = "1.0.158"
description = "Next toolkit for python."
authors = ["feizheng <1290657123@qq.com>"]
readme = "README.md"
repository = "https://github.com/aric-pypi/jsw-nx"
homepage = "https://js.work"

[tool.poetry.dependencies]
python = "^3.7"
psutil = "^5.9.0"
"ruamel.yaml" = "^0.17.21"
bs4 = "^0.0.1"
requests = "^2.28.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
