[project]
name = "distortions"
version = "0.0.4"
authors = [
  { name="Kris Sankaran", email="ksankaran@wisc.edu" },
  { name="Shuzhen Zhang", email="shuzhenz@uw.edu" },
  { name="Chenab", email="chenab@uw.edu" },
  { name="Marina Meila", email="mmp@uwaterloo.ca" }
]
description = "Interactive visualization of distortion in nonlinear embeddings."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "CC-BY-4.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
plotting = ["altair"]

[project.urls]
Homepage = "https://github.com/krisrs1128/distortions/"
Issues = "https://github.com/krisrs1128/distortions/Issues/"

[build-system]
requires = ["anywidget", "hatchling", "scipy", "traitlets"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["distortions"]
exclude = [
  "docs/tutorials/data/",
  "site/",
]

[tool.hatch.build.targets.sdist]
exclude = [
  "docs/tutorials/data/",
  "site/",
]