[project]
name = "hamplots"
version = "1.0.25"
license = "MIT"
description = "Realtime plots for ham radio band conditions"
authors = [{name="G1OJS", email="g1ojs@yahoo.com"}]
readme = {file = 'README.md', content-type='text/markdown'}
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "pandas",
    "numpy",
    "paho-mqtt",
    "pathlib"
]



keywords = []

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/G1OJS/hamplots"
Issues = "https://github.com/G1OJS/hamplots/issues"

[project.scripts]
hamplots = "hamplots:get_args_and_run"

[tool.setuptools.packages.find]
where = ["."]
