[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sarathii"      # change to your package name
version = "0.7.0"
description = "A sample package published using Flit"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE.txt" }
authors = [
    { name = "Vijayasarathi", email = "vijayasarathi871@gmail.com" }
]
dependencies = [
    # Example dependency: "requests>=2.0"
]

