[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "txgraffiti"
version = "0.3.1"
description = "A Python package for automated mathematical conjecturing"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [{ name = "Randy Davila" }, { name = "Jillian Eddy" }]
dependencies = ["pandas", "numpy", "scipy", "pulp", "networkx", "graphcalc"]

[project.urls]
Homepage = "https://github.com/RandyRDavila/txgraffiti2"
Documentation = "https://txgraffiti.readthedocs.io"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "coverage",
    "pandas",
    "numpy",
    "scipy",
    "pulp",
    "networkx",
    "graphcalc",
]


[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true

[tool.pytest.ini_options]
addopts = "--doctest-modules"
