[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rrhfoem04-lib"
version = "0.0.5"
authors = [
  { name="ajxv" },
]
description = "Python Library for interfacing with the RRHFOEM04 RFID Reader"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.12"
dependencies = [
  "hidapi==0.14.0.post4",
  "setuptools==75.6.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Other Audience"
]

[project.urls]
Repository = "https://github.com/ajxv/rrhfoem04-lib"
Issues = "https://github.com/ajxv/rrhfoem04-lib/issues"