[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "bioreactor_model"
version = "0.0.8"
dependencies = [
  "numpy"
]
authors = [
  { name="Noorul Ali", email="manonthemoon13131@gmail.com" },
]
description = "Bioreactor-model is a Python package for bioreactor and biomass growth calculations"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "Operating System :: OS Independent",
]
license = "CC0-1.0"
license-files = ["LICENSE*"]

[project.urls]
Homepage = "https://asbldex.github.io"
Documentation = "https://matrixdex.github.io/bioreactor-model/"
Issues = "https://github.com/matrixdex/bioreactor-model/issues"
Repository = "https://github.com/matrixdex/bioreactor-model"