[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "osintplus"
version = "0.1.1"
description = "Outil de renseignement OSINT en ligne de commande, sans utiliser d'API"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "root10"}
]
keywords = ["osint", "cli", "reconnaissance", "cybersecurity"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

dependencies = [
    "requests",
    "python-whois",
    "colorama",
    "tqdm"
]

[project.scripts]
osintplus = "osintplus.cli:main"
