mod:
  mindgo:
    lib: supermind.mod.mindgo
    enabled: true
  stock:
    lib: supermind.mod.stock
    enabled: false
  stock_paper:
    lib: supermind.mod.stock_paper
    enabled: false
  analyser:
    lib: supermind.mod.analyser
    enabled: false
  realtime:
    lib: supermind.mod.realtime
    enabled: false