[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "find-executable"
version = "0.1.0a0"
description = "A Python package that provides cross-platform executable path resolution. Like Unix `which` command but better."
readme = "README.md"
requires-python = ">=2"
license = "MIT"
authors = [
  { name="Jifeng Wu", email="jifengwu2k@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "posix-or-nt"
]

[project.urls]
"Homepage" = "https://github.com/jifengwu2k/find-executable"
"Bug Tracker" = "https://github.com/jifengwu2k/find-executable/issues"