[project]
name = "sciop-scraping"
dynamic = []
description = "scraping code to use with sciop-coordinated scrapes"
authors = [
    { name = "sneakers-the-rat", email = "sneakers-the-rat@protonmail.com" },
]
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "sciop-cli>=0.2.0",
    "click>=8.2.1",
    "scrapy>=2.13.0",
    "tqdm>=4.67.1",
]
version = "0.3.0"

[project.license]
text = "EUPL-1.2"

[project.scripts]
sciop-scrape = "sciop_scraping.cli.main:cli"

[project.urls]
repository = "https://codeberg.org/safeguarding/sciop-scraping"
homepage = "https://codeberg.org/safeguarding/sciop-scraping"

[project.optional-dependencies]
test = [
    "pytest>=8.3.5",
    "bagit>=1.9.0",
]
dev = [
    "black>=25.1.0",
    "ruff>=0.12.4",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
test = "pytest"

[tool.pdm.scripts.lint]
composite = [
    "ruff check",
    "black . --diff",
]

[tool.pdm.scripts.format]
composite = [
    "black .",
    "ruff check --fix",
]

[tool.pdm.version]
source = "scm"
tag_filter = "v*"
tag_regex = "v(?P<version>([1-9][0-9]*!)?(0|[1-9][0-9]*)(\\.(0|[1-9][0-9]*))*((a|b|c|rc)(0|[1-9][0-9]*))?(\\.post(0|[1-9][0-9]*))?(\\.dev(0|[1-9][0-9]*))?$)$"

[tool.ruff]
target-version = "py311"
include = [
    "src/sciop_scraping/**/*.py",
    "tests/**/*.py",
    "pyproject.toml",
]
exclude = []
line-length = 100

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
    "ANN",
    "T10",
    "D207",
    "D208",
    "D210",
    "D211",
    "D419",
    "N802",
    "FAST",
    "S608",
    "S701",
]
ignore = [
    "ANN401",
    "ANN204",
    "B905",
    "D107",
]
fixable = [
    "ALL",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/test_*" = [
    "ANN001",
    "ANN201",
    "F841",
]
"tests/conftest.py" = [
    "E402",
    "F401",
    "F403",
]
"tests/fixtures/**/*" = [
    "F403",
]

[tool.black]
target-version = [
    "py311",
    "py312",
    "py313",
]
include = "(?:tests|sciop_scraping)/.*\\.py$"
line-length = 100
