[project]
name = "semanticlens"
version = "0.2.0"
description = "A package for mechanistic understanding and validation of large  AI model with SemanticLens"
readme = "README.md"
authors = [
    { name = "Jim Berend", email = "jim.berend@hhi.fraunhofer.de" },
    { name = "Maximilian Dreyer", email = "maximilian.dreyer@hhi.fraunhofer.de" },
]
keywords = [
    "mechanistic interpretability",
    "semantic analysis",
    "foundation model",
    "deep learning",
]
license = "BSD-3-Clause"
requires-python = ">=3.9"
dependencies = [
    "einops>=0.8.1",
    "open-clip-torch>=3.0.0",
    "scikit-learn>=1.6.1",
    "timm>=1.0.19",
    "torch>=2.7.1",
    "transformers>=4.54.1",
    "zennit-crp>=0.6.0",
]

[dependency-groups]
dev = [
    "furo>=2025.7.19",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
    "sphinx>=7.4.7",
    "sphinx-rtd-theme>=3.0.2",
    "tox>=4.28.4",
    "tox-uv>=1.27.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["D205", "D200", "D204", "D401"]
extend-select = [
    "UP", # pyupgrade
    "D",  # pydocstyle
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
