[project]
name = "pystartgg"
version = "0.0.16"
description = "Python wrapper for startgg API calls."
authors = [
    {name = "Steven",email = "shepsteven42@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["requests"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
