[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "drap"
version = "0.0.3.post2"
description = "Tool for analyzing droplet size and concentration using video and EDF images"
readme = "README.md"
license = {text = "MIT"}
authors = [{ name = "Gabriel Braga Marques Teobaldo, Oleg Prymak, Natalie Wolff,  Matthias Epple, Marco Aurélio Brizzotti Andrade, Cássio Alves and Cristiano Luis Pinto de Oliveira", email = "alves.casssio@gmail.com" }]
requires-python = ">=3.8"

dependencies = [
    "opencv-python",
    "numpy",
    "matplotlib",
    "fabio",
    "pillow",
    "reportlab",
    "PyQt5"
]

keywords = ["saxs", "x-ray", "edf", "opencv", "pyqt5", "droplet"]

[project.scripts]
drap = "drap.main:main"
drap-gui = "drap.gui:gui" 

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://test.pypi.org/project/DrAP/"
Source = "https://test.pypi.org/project/DrAP/"
