[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pendragondi-cloud-audit"
version = "0.3.3"
description = "PendragonDI Cloud Audit â€“ local tool to detect stale, redundant, or inefficient storage in cloud buckets."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [{name = "jinpendragon", email = "pendragondi@pendragondi.dev"}]
dependencies = ["typer"]

[project.optional-dependencies]
aws = ["boto3"]
gcs = ["google-cloud-storage"]
azure = ["azure-storage-blob"]
all = ["boto3", "google-cloud-storage", "azure-storage-blob"]

[project.scripts]
pendragondi-cloud-audit = "pendragondi_cloud_audit.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pendragondi_cloud_audit", "pendragondi_cloud_audit.providers"]

