[project]
name = "bpandas"
version = "0.1.5"
description = "Funções utilitárias para facilitar o uso do pandas"
authors = [
    { name = "David Closs", email = "100291464+davidcloss@users.noreply.github.com" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = ["pandas==2.3.1", "matplotlib==3.10.5", "numpy==2.3.2"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "==8.4.1"
