[project]
name = "dweb"
version = "0.2.1"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "autonomi-client (>=0.5.3,<0.6.0)"
]


[tool.poetry]
packages = [
    { include = "dweb" }
]
include = [
    "dweb/py.typed",
    "dweb/autonomi.pyi",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.23.8"
pytest-timeout = "^2.3.1"
pytest-cov = "^5.0.0"
mypy = "^1.11.1"
types-python-dateutil = "^2.9.0.20240316"
python-dotenv = "^1.0.1"

[tool.poetry.group.notebooks]
optional = true

[tool.poetry.group.notebooks.dependencies]
ipykernel = "^6.29.5"
jupyterlab = "^4.2.4"
ipython = "^8.26.0"
Pillow = "^10.4.0"
