[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xsd2doc"
version = "0.1.0"
description = "xsd2doc: A tool to generate markdown documentation from XSD files."
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name="YammyToast" }]
requires-python= ">=3.9"
dependencies = [
    "jinja2",
    "pyyaml"
]

[project.scripts]
xsd2doc = "xsd2doc.main:main"

[tool.setuptools.package-data]
"xsd2doc" = ["templates/*.j2"]