[project]
name = "spryx-message"
version = "0.1.4"
description = ""
authors = [
    {name = "Luiz Henrique",email = "luiz@spryx.ai"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "spryx-http (>=0.2.7)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
doppler-env = "^0.3.1"

