[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mofo"
version = "0.1.1"
description = "A Python library for model FLOPs and throughput benchmarking"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name="17fine", email="2756601885@qq.com"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch",
    "torchvision",
    "thop",
    "torchinfo"
]
