[tool.poetry]
name = "syrius-sdk"
version = "0.2.87"
description = "The Python SDK for Syrius Flow Engine"
license = "BSD-3-Clause"
authors = ["Andrea Mucci <andrea@clariteia.com>"]
readme = "README.md"
packages= [{include = "syrius"}]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP"
]
[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.6.1"
httpx = "^0.27.0"

[project]
requires-python = ">=3.10"
name = "syrius-sdk"
version = "0.2.87"
dependencies = ["pydantic", "httpx"]
description = "The Python SDK for Syrius Flow Engine"
license = {text = "BSD-3-Clause"}
authors = [
  {name = "Andrea Mucci", email = "andrea@clariteia.com"}
]
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP"
]

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
uvicorn = "^0.27.1"
coverage = "^7.4.2"

[tool.setuptools]
packages = ["syrius", "syrius.commands", "syrius.loops"]

[build-system]
requires = ["setuptools>=70.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = ["venv/*"]
include = ["syrius/*", "tests/*"]

[tool.bumpver]
current_version = "0.2.87"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
    'version = "{version}"'
]

