[project]
name = "atomic-mcp"
version = "0.1.5"
description = "A framework for building MCP Servers using Atomic Agents and FastMCP"
authors = [
    {name = "jon fox",email = "jon@foxsolutions.dev"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = "<4.0,>=3.12"
dependencies = [
    "atomic-agents (>=2.0.1,<3.0.0)",
    "fastmcp (>=2.11.0,<3.0.0)"
]

[project.scripts]
atomic-mcp = "atomic_mcp.cli.main:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.3.0"
pytest = "^8.4.1"
pytest-asyncio = "^1.1.0"
pytest-cov = "^6.2.1"

