repo:
  file_filters:
    excluded_dirs:
      - "*/.venv/*"
      - "*/env/*"
      - "*/virtualenv/*"
      - "*/node_modules/*"
      - "*/bower_components/*"
      - "*/jspm_packages/*"
      - "*/.git/*"
      - "*/.svn/*"
      - "*/.hg/*"
      - "*/.bzr/*"
      - "*/__pycache__/*"
      - "*/build*/*"
      - "*/dist*/*"
      - "*/bower_components/*"
      - "*/jspm_packages/*"
      - "*/lib-cov/*"
      - "*/htmlcov/*"
      - "*/bin*/*"
      - "*/out*/*"
    excluded_files:
      - "*yarn.lock"
      - "*pnpm-lock.yaml"
      - "*npm-shrinkwrap.json"
      - "*poetry.lock"
      - "*Pipfile.lock"
      - "*requirements.txt.lock"
      - "*Cargo.lock"
      - "*composer.lock"
      - "*.lock"
      - "*.DS_Store"
      - "*.Thumbs.db"
      - "*desktop.ini"
      - "*.lnk"
      - "*.env.*"
      - "*.env"
      - "*.cfg"
      - "*.ini" 
      - "*.flaskenv"
      - "*.gitignore"
      - "*.gitattributes"
      - "*.gitmodules"
      - "*.github"
      - "*.gitlab-ci.yml"
      - "*.prettierrc"
      - "*.eslintrc"
      - "*.eslintignore"
      - "*.stylelintrc"
      - "*.editorconfig"
      - "*.jshintrc"
      - "*.pylintrc"
      - "*.flake8"
      - "*mypy.ini"
      - "*pyproject.toml"
      - "*tsconfig.json"
      - "*webpack.config.js"
      - "*babel.config.js"
      - "*rollup.config.js"
      - "*jest.config.js"
      - "*karma.conf.js"
      - "*vite.config.js"
      - "*next.config.js"
      - "*.min.js"
      - "*.min.css"
      - "*.bundle.js"
      - "*.bundle.css"
      - "*.map"
      - "*.gz"
      - "*.zip"
      - "*.tar"
      - "*.tgz"
      - "*.rar"
      - "*.7z"
      - "*.iso"
      - "*.dmg"
      - "*.img"
      - "*.msix"
      - "*.appx"
      - "*.appxbundle"
      - "*.xap"
      - "*.ipa"
      - "*.deb"
      - "*.rpm"
      - "*.msi"
      - "*.exe"
      - "*.dll"
      - "*.so"
      - "*.dylib"
      - "*.o"
      - "*.obj"
      - "*.jar"
      - "*.war"
      - "*.ear"
      - "*.jsm"
      - "*.class"
      - "*.pyc"
      - "*.pyd"
      - "*.pyo"
      - "*.a"
      - "*.lib"
      - "*.lo"
      - "*.la"
      - "*.slo"
      - "*.dSYM"
      - "*.egg"
      - "*.egg-info"
      - "*.dist-info"
      - "*.eggs"
      - "*.nyc_output"
      - "*.tox"
      - "*output"
    included_dirs: []
    included_files: []

  repository:
    max_size_mb: 50000

  file_extensions:
    code_extensions:
      - ".py"
      - ".js"
      - ".ts"
      - ".java"
      - ".cpp"
      - ".c"
      - ".h"
      - ".hpp"
      - ".go"
      - ".rs"
      - ".jsx"
      - ".tsx"
      - ".html"
      - ".css"
      - ".php"
      - ".swift"
      - ".cs"
      - ".sol"
      - ".ml"
      - ".mli"
      - ".hs"
      - ".lhs"
      - ".fs"
      - ".fsi"
      - ".fsx"
      - ".erl"
      - ".hrl"
      - ".ex"
      - ".exs"
      - ".clj"
      - ".cljs"
      - ".cljc"
      - ".scm"
      - ".ss"
      - ".lisp"
      - ".lsp"
      - ".elm"
      - ".rb"
      - ".pl"
      - ".pm"
      - ".scala"
      - ".sc"
      - ".kt"
      - ".kts"
      - ".dart"
      - ".lua"
      - ".r"
      - ".R"
      - ".m"
      - ".jl"
      - ".nim"
      - ".cr"
      - ".zig"
      - ".v"
      - ".sv"
      - ".vhd"
      - ".vhdl"
      - ".s"
      - ".S"
      - ".asm"
      - ".sh"
      - ".bash"
      - ".zsh"
      - ".fish"
      - ".ps1"
      - ".psm1"
      - ".bat"
      - ".cmd"
      - ".toml"
      - ".ini"
      - ".cfg"
      - ".conf"
      - ".xml"
      - ".xaml"
      - ".proto"
      - ".graphql"
      - ".gql"
      - ".sql"
      - ".mk"
      - ".cmake"
      - ".gradle"
      - ".sbt"
      - ".bazel"
      - ".bzl"
      - ".md"
      - ".markdown"
      - ".mdown"
      - ".mkd"
      - ".mkdn"
      - ".rst"
      - ".json"
      - ".jsonl"
      - ".yaml"
      - ".yml"
      - ".toml"
      - ".ini"
      - ".cfg"
      - ".conf"
      - ".xml"
    doc_extensions:
      - ".txt"