[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "finnslib"
version = "0.1.2"
description = "small tools to print repo trees and make code summaries"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Finn Clancy", email = "finnnclancy2000@gmail.com" }]
keywords = ["tree", "gitignore", "summary", "llm", "code"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = ["openai>=1.0"]

[tool.setuptools.packages.find]
include = ["finnslib", "finnslib.*"]
where = ["."]

[project.scripts]
finn_tree = "finnslib.repo.tree:write_repo_tree"
finn_tree_sum = "finnslib.summarise.tree_with_files:summarise_repo_tree"
finn_file_sum = "finnslib.summarise.file:summarise_file"
finn_func_sum = "finnslib.summarise.function:summarise_function"