[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "minimum-pipeline"
version = "1.2.1"
description = "Data pipeline: extract → classify → clean → split."
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Daniel Valdez"}]
license = {text = "MIT"}
dependencies = [
  "pandas>=2.3.1",
  "numpy>=2.1",
  "scikit-learn>=1.7.1"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
minimum-pipeline = "minimum_pipeline.cli:main"


# --- NUEVO: configuración para python-semantic-release ---
[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = "master"
tag_format = "v{version}"
upload_to_pypi = false          # publicamos con twine en el workflow
build_command = "python -m build"
changelog_file = "CHANGELOG.md"

[tool.semantic_release.commit_parser_options]
major_tags = ["BREAKING CHANGE", "!:"]  # Conventional Commits