[project]
name = "lanchain-sgframework"
version = "0.1.1"
description = "LangChain Helper Library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.27",
    "langchain-mcp-adapters>=0.1.9",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "lanchain-sgframework"

[dependency-groups]
dev = [
    "setuptools>=80.9.0",
]
