[project]
name = "dwarfbind"
version = "0.1.4"
description = "Generate Python ctypes bindings from shared libraries"
authors = [
    {name = "Ray Strode", email = "rstrode@redhat.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "pyelftools>=0.32",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
markers = [
    "integration: marks tests that interact with real system components",
]

[tool.hatch.build.targets.wheel]
packages = ["dwarfbind"]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.9",
]

[project.scripts]
dwarfbind = "dwarfbind.cli:main"
