[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cmd_habit_tracker"
version = "1.0.3"
description = "Command-line habit tracker with AI suggestions, customizable tracking, and user-friendly interface."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE.MIT" }
authors = [
    { name = "Abdalla Egbareia", email = "habitcmd@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = [
    "habit-tracker",
    "cli",
    "command-line",
    "productivity",
    "time-management",
    "goal-tracking",
    "habit-building",
    "ai-suggestions",
    "personal-development",
    "self-improvement",
    "tracking-tool",
    "customizable",
    "user-friendly",
    "python"
]
dependencies = [
    "pandas",
    "tabulate",
    "requests",
    "platformdirs"
]

[project.urls]
Homepage = "https://github.com/abdallacodes/cmd-habit-tracker.git"

[project.scripts]
habits = "cmd_habit_tracker.main:main"

[tool.hatch.build]
include = [
    "README.md"
]

[tool.hatch.build.targets.wheel]
packages = ["cmd_habit_tracker"]
