# BUILD

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Poetry

# Information required for building (sdist/wheel)
## Also renders on pypi as 'subtitle'
[tool.poetry]
name = "qumas"
version = "0.1.0"
description = "SHEAP: Spectral Handling and Estimation of AGN Parameters"
authors = ["Felipe Avila-Vera <felipe.avilav@postgrado.uv.cl>"]
maintainers = ["Felipe Avila-Vera <felipe.avilav@postgrado.uv.cl>"]
license = "AGPL-3.0-only"
readme = "README.rst"

homepage = "https://github.com/favila/qumas"
repository = "https://github.com/favila/qumas"
documentation = "https://qumas.readthedocs.io/"

keywords = [
    "python package",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Software Distribution",
    "Typing :: Typed"
]

packages = [
    { include = "qumas" },
]

include = [
    { path = "tests", format = "sdist" },
    { path = "docs/**/*.rst", format = "sdist" },
    { path = "docs/conf.py", format = "sdist" },
    { path = "qumas/**/*.typed", format = "sdist" },
    { path = "qumas/stubs/*.pyi", format = "sdist" },
    "pyproject.toml",
    "LICENSE",
    "README.rst",
    "CONTRIBUTING.md",
    "CHANGELOG.rst",
]

exclude = [
    "docs/*",
    "requirements/*",
    "scripts/*.py",
    "tox.ini",
    ".circleci/config.yml",
    ".coveragerc",
    ".DS_Store",
    ".gitignore",
    ".prospector.yml",
    ".pylintrc",
    ".readthedocs.yml",
    ".scrutinizer.yml",
    ".travis.yml"
]

# PyPi url links, that appear in 'Project Links' section
[tool.poetry.urls]
"Bug Tracker" = "https://github.com/qumas/issues"
"CI: Github Actions" = "https://github.com/favila/qumas/actions"
"Documentation" = "https://qumas.readthedocs.io/"
"Source Code" = "https://github.com/favila/qumas"
"Changelog" = "https://github.com/favila/qumas/blob/master/CHANGELOG.rst"
"Code of Conduct" = "https://github.com/favila/qumas/blob/master/CONTRIBUTING.rst"


# Caret requirements allow SemVer compatible updates to a specified version. An update is allowed if the new version number does not modify the left-most non-zero digit in the major, minor, patch grouping. For instance, if we previously ran poetry add requests@^2.13.0 and wanted to update the library and ran poetry update requests, poetry would update us to version 2.14.0 if it was available, but would not update us to 3.0.0. If instead we had specified the version string as ^0.1.13, poetry would update to 0.1.14 but not 0.2.0. 0.0.x is not considered compatible with any other version.
# REQUIREMENT  VERSIONS ALLOWED
# ^1.2.3	   >=1.2.3 <2.0.0
# ^1.2	       >=1.2.0 <2.0.0
# ^1	       >=1.0.0 <2.0.0
# ^0.2.3	   >=0.2.3 <0.3.0
# ^0.0.3	   >=0.0.3 <0.0.4
# ^0.0	       >=0.0.0 <0.1.0
# ^0	       >=0.0.0 <1.0.0
# "~" is the more conservative compared to "^"
# Tilde requirements specify a minimal version with some ability to update. If you specify a major, minor, and patch version or only a major and minor version, only patch-level changes are allowed. If you only specify a major version, then minor- and patch-level changes are allowed.
# REQUIREMENT  VERSIONS ALLOWED
# ~1.2.3	   >=1.2.3 <1.3.0
# ~1.2	       >=1.2.0 <1.3.0
# ~1	       >=1.0.0 <2.0.0


### Dependency Constraints, aka Requirements ###
[tool.poetry.dependencies]
python =  ">=3.9,<3.13"
astropy = ">=6.0"
scipy = ">=1.11.4"
pandas = ">=2.2.0"
matplotlib = ">=3.8.2"
parallelbar = ">=2.4"
numpy = "==1.26"
lmfit = "*"
h5py = "*"

# Test: packages imported in test code and packages required for the "test runner"
pytest = { version = "^8.0.0", optional = true }
pytest-cov = { version = "^4.1.0", optional = true }
pytest-explicit = { version = "^1.0.1", optional = true }
pytest-xdist = { version = "^3.5.0", optional = true }
pytest-click = { version = "^1.1.0", optional = true }
pytest-run-subprocess = { version = "^0.10.0", optional = true }

# Type Checking
mypy = { version = "^1.8.0", optional = true }

# Docs: dev and build dependencies
sphinx = { version = ">=5.0,<8.3", optional = true }
sphinx-autodoc-typehints = { version = ">=1.10", optional = true }
sphinx-rtd-theme = { version = ">=1.2.0,<2.0", optional = true }
sphinxcontrib-spelling = { version = "~=7.3.3", optional = true }
sphinx-autobuild = { version = "^2021.3.14", optional = true }
sphinx-inline-tabs = { version = "^2023.4.21", optional = true, python = ">=3.12,<3.13" }
sphinxcontrib-mermaid = { version = "^0.9.2", optional = true, python = ">=3.12,<3.13" }
nbsphinx = "*"
myst_nb = "*"
# requests [security,tests] >= 2.8.1, == 2.8.* ; python_version < "2.7"
# poetry add 'griffe >=1.0.0 ; python_version >= "3.9"' --optional


### EXTRAS ###
[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
pytest-cov = "^4.0"
pytest-xdist = "^3.0"
coverage = "^7.0"
exceptiongroup = "^1.1" 
sphinx = ">=5.0"
click = { version = ">=8.1.0,<9.0", optional = true }
types-pyyaml = "^6.0.12.20250516"
nbsphinx = "*"
myst_nb = "*"

[tool.poetry.extras]
test = [
    "pytest",
    "pytest-cov",
    "pytest-explicit",
    "pytest-xdist",
    "pytest-click",
    "pytest-run-subprocess",
    "coverage"
    ,"exceptiongroup"]
typing = [
    "mypy",
    "types-requests",
    "pytest",
    "pytest-click",
]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "sphinxcontrib-spelling",
    "sphinx-inline-tabs",
    "sphinxcontrib-mermaid",
    "furo",
    "sphinx-autobuild"
    ,"nbsphinx","myst-parser","myst_nb"
    
    
]
docslive = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "sphinxcontrib-spelling",
    "sphinx-inline-tabs",
    "sphinxcontrib-mermaid",
    "sphinx-autobuild","nbsphinx","myst-parser","myst_nb"
]

[tool.poetry.scripts]
qumas = 'qumas.cli:main'

[tool.poetry.plugins."poetry.application.plugin"]
export = "poetry_plugin_export.plugins:ExportApplicationPlugin"

# TOOLS

[tool.poetry.group.typing.dependencies]
types-pyyaml = "^6.0.12.20250402"

[tool.pytest.ini_options]
minversion = "6.2"
addopts = "--strict-markers"
markers = [
    "slow: Marks a slow test",
    "integration: Integration Tests",
    "network_bound: Require internet connection",
]
testpaths = [
    "tests",
]
explicit-only = [
    "integration",
    "network_bound",
]

[tool.black]
line-length = 95
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = 'black'

[tool.bandit]
tests = []
skips = [
    "B101",
]

[tool.mypy]
ignore_missing_imports = true      # quick blanket, or â€¦
check_untyped_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
ignore_errors = true

[[tool.mypy.overrides]]
module = ["astropy.*"]
ignore_missing_imports = true

[tool.software-release]
version_variable = "qumas/__init__.py:__version__"