[project]
name = "biomarker-mcp"
dynamic = ["version"]
description = "Natural language interface for celltype marker query through MCP."
readme = "README.md"
authors = [
    { name = "shuang", email = "hsh-me@outlook.com" }
]

keywords = [
    "mcp",
    "model context protocol",
    "llm",
    "agent",
    "scRNA-seq",
    "single cell",
    "bioinformatics",
    "celltype",
    "gene marker",
    "biomarker",
    "AI"
]

requires-python = ">=3.10"
dependencies = [
    "mcp>=1.8.0",
    "fastmcp>=2.3.4",
    "nest_asyncio",
    "scanpy",
    "typer"
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
    "pytest-asyncio>=0.23.5",
]

[project.scripts]
biomarker-mcp = "biomarker_mcp.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/biomarker_mcp/__init__.py"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[project.urls]
Homepage = "https://github.com/scmcphub/biomarker-mcp"
Repository = "https://github.com/scmcphub/biomarker-mcp"
