[project]
name = "jira-creator"
version = "1.0.11"
description = "CLI and tools to automate JIRA issue creation"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
authors = [
  { name = "David O Neill", email = "dmz.oneill@gmail.com" }
]
dependencies = []

[project.scripts]
jira-creator = "jira_creator.rh_jira:main"

[build-system]
requires = [
  "setuptools>=78.0.0",
  "packaging>=24.2"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | jira_config
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "too-many-instance-attributes",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-few-public-methods",
    "duplicate-code",
    "import-outside-toplevel",
]

[tool.flake8]
max-line-length = 120
ignore = ["E203", "E501", "W503", "F401"]
exclude = [".git", "__pycache__", "build", "dist"]
