[project]
name = "FHIL_python_utils"
dynamic = ["version"]
authors = [
  { name="Derrik Gratz", email="derrik.gratz@gmail.com" },
]
description = "General utility functions for Python data analysis and visualization"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "pandas",
  "numpy",
  "scanpy",
  "seaborn",
  "matplotlib",
  "pybiomart",
  "anndata"
]

[tool.hatch.build.targets.wheel]
packages = ["src/FHIL_python_utils"]

[tool.hatch.version]
path = "src/FHIL_python_utils/__init__.py"



[dependency-groups]
svm = ["sklearn"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Fred-Hutch-Innovation-Lab/python_utils"
Issues = "https://github.com/Fred-Hutch-Innovation-Lab/python_utils/issues"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
