[build-system]
requires = [
  "hatchling>=1.18"
]
build-backend = "hatchling.build"

[project]
name = "ctlib-webstack"
version = "0.1.0"
description = "A collection of common web middlewares for security and request processing."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name = "Jimin", email = "jimin@codetech.top" }
]
dependencies = [
  "starlette>=0.27",
  "ctlib-geoip>=0.1.0",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Framework :: AsyncIO",
]

[project.optional-dependencies]
fastapi = [
  "fastapi>=0.103",
  "pydantic>=2",
]

[project.urls]
Homepage = "https://git.codetech.top/ctlib/ctlib-webstack"
Repository = "https://git.codetech.top/ctlib/ctlib-webstack"

[tool.hatch.build.targets.wheel]
packages = [
  "src/ctlib_webstack"
]


