[project]
name = "mcp-servers123456-demo"
version = "0.1.11"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.10.1",
]


[project.scripts]
mcp-servers123456-demo = "mcp_servers123456_demo.test:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
