[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "falconpy2"
version = "2.0.0"
description = "FalconPy2â€"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "NetrisCS" }]
license = { text = "Unlicense" }
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: Public Domain",
]

[project.urls]
Homepage = "https://www.netriscs.com/"

[tool.setuptools.packages.find]
where = ["src"]
include = ["falconpy*"]
exclude = ["tests*"]
